name: PullRequest Checker

on:
  push:
  pull_request_target:
    types: [opened, closed]
    paths-ignore:
      - 'docs/**'

jobs:
  output-log:
    runs-on: ubuntu-latest
    steps:
      - name: github.pull_request
        run: echo "${{ github.event.pull_request }}"
      - name: headRef
        run: echo "${{ github.event.pull_request.headRef }}"
      - name: headRepositoryOwner
        run: echo "${{ github.event.pull_request.headRepositoryOwner }}"
      - name: headRepositoryOwner
        run: echo "${{ github.event.pull_request.headRepositoryOwner }}"
      - name: commits
        run: echo "${{ github.event.pull_request.commits }}"
